version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=critipixel
      - MYSQL_USER=critipixel
      - MYSQL_PASSWORD=critipixel

volumes:
  mysql_db:
    driver: local
