name: CI workflow
on:
  pull_request:

env:
  PHP_VERSION: '8.4'
  POSTGRES_VERSION: '16-alpine'

jobs:
  build:
    name: ğŸ”§ Build Environment
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4
      - name: ğŸ˜ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: ğŸ“š Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: ğŸ—„ï¸ Create database
        run: php bin/console doctrine:database:create --env=test
      - name: ğŸ”„ Run migrations
        run: php bin/console doctrine:migrations:migrate -n --env=test
      - name: ğŸŒ± Load fixtures
        run: php bin/console doctrine:fixtures:load -n --purge-with-truncate --env=test
      - name: ğŸ¨ Build assets
        run: php bin/console sass:build
      - name: ğŸ“¤ Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: symfony-env
          path: |
            vendor/
            var/cache/test/
            public/build/
          retention-days: 1

  phpstan:
    name: ğŸ” PHPStan static analysis
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4
      - name: ğŸ˜ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: ğŸ“¥ Download artifact
        uses: actions/download-artifact@v4
        with:
          name: symfony-env
      - name: ğŸ” Run PHPStan
        run: php vendor/bin/phpstan analyse --no-progress --error-format=github

  cs-fixer:
    name: âœ¨ Code Style (PHP-CS-Fixer)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4
      - name: ğŸ˜ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: ğŸ“¥ Download artifact
        uses: actions/download-artifact@v4
        with:
          name: symfony-env
      - name: âœ¨ Run PHP-CS-Fixer
        run: php vendor/bin/php-cs-fixer fix --dry-run --diff --format=github

  phpunit:
    name: ğŸ§ª Unit tests with PHPUnit
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4
      - name: ğŸ˜ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: ğŸ“¥ Download artifact
        uses: actions/download-artifact@v4
        with:
          name: symfony-env
      - name: ğŸ§ª Run PHPUnit
        run: php vendor/bin/phpunit